region: "eu-north-1"
aws_secret_name: "maria-db-creds"
aws_secret_version: "AWSCURRENT"
vault_create_secret: false
vault_host: "http://127.0.0.1:8082"
vault_token: ""
vault_mount_path: "" # initial path of yours KV engine in vault
vault_dir_name: "" # name of directory with key-value secrets
kube_secret_namespace: "default" 
kube_secret_name: "secret-test"